name: mlp_ads
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - jupyter
  - jupyterlab
  - numpy
  - scipy
  - pandas
  - ase
  - gemmi
  - pymatgen
  - tqdm
  - simplejson
  - pip:
    - pymser
    - mace-torch
    - torch-dftd
